name: CI

on:
  pull_request:
    branches: ['develop']
  push:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      # - run: npm run test -- --coverage
      #   env:
      #     CI: true
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
        env:
          CI: false
      - name: Deploy to staging Netlify
        if: github.event_name == 'push'
        # uses: South-Paw/action-netlify-deploy@v1.2.0
        run: netlify deploy --dir=public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
